# Remember to setup a .env alongside this file
# that provides the values for MYSQL_ROOT_PASSWORD 
# and others. The format is:
# P4_USERNAME=myadminuser
# P4_PASSWORD=myadminpassword
# SWARM_USER_NAME=myswarmuser
# SWARM_PASSWORD=myswarmpassword
# SWARM_TRIGGER_TOKEN=mytriggertoken


version: '2.1'
services:
  p4d:
    image: hawkmothstudio/helix-p4d
    build: helix-p4d
    ports:
      - '1666:1666'
    environment:
      P4USER: ${P4_USERNAME}
      P4PASSWD: ${P4_PASSWORD}
      P4D_USE_UNICODE: 'true'
      P4D_LOAD_TYPEMAPS: 'false'
      P4D_LOAD_USERS: 'false'
      P4D_LOAD_USER_PASSWORDS: 'false'
      P4D_LOAD_GROUPS: 'false'
      P4D_LOAD_DEPOTS: 'false'
      P4D_LOAD_PROTECTIONS: 'false'
      SWARM_URL: 'http://localhost'
      INSTALL_SWARM_TRIGGER: 'true'
      SWARM_TRIGGER_TOKEN: ${SWARM_TRIGGER_TOKEN}
    volumes:
      - /opt/p4data/p4d_data:/data
  swarm:
    image: hawkmothstudio/helix-swarm
    build: helix-swarm
    ports:
      - '1667:80'
    environment:
      P4PORT: 'ssl:p4d:1666'
      P4USER: ${P4_USERNAME}
      P4PASSWD: ${P4_PASSWORD}
      P4D_USE_UNICODE: 'true'
      SWARM_USER: ${SWARM_USER_NAME}
      SWARM_PASSWD: ${SWARM_PASSWORD}
      SWARM_USER_CREATE: 'false'
      SWARM_GROUP_CREATE: 'false'
      SWARM_HOST: 'localhost'
      SWARM_PORT: '80'
      SWARM_TRIGGER_TOKEN: ${SWARM_TRIGGER_TOKEN}
    volumes:
      - /opt/p4data/swarm_data:/opt/perforce/swarm/data
    depends_on:
      - p4d
