name: ci

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set image tags for helix-p4d
        id: p4d_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: hawkmothstudio/helix-p4d
          tag-semver: |
            {{version}}
            {{major.minor}}
            {{major}}
      - name: Set image tags for helix-swarm
        id: swarm_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: hawkmothstudio/helix-swarm
          tag-semver: |
            {{version}}
            {{major.minor}}
            {{major}}

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push helix-p4d
        uses: docker/build-push-action@v2
        with:
          context: helix-p4d
          file: ./helix-p4d/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.p4d_meta.outputs.tags }}
          labels: ${{ steps.p4d_meta.outputs.labels }}
      - name: Build and push helix-swarm
        uses: docker/build-push-action@v2
        with:
          context: helix-swarm
          file: ./helix-swarm/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.swarm_meta.outputs.tags }}
          labels: ${{ steps.swarm_meta.outputs.labels }}
